// =============================================================================
// UpdateStreakUseCase — Application Layer Use Case
// =============================================================================
// Handles streak calculation whenever a user performs an activity (solves a
// problem, completes an MCQ, etc.) on a topic.
//
// Streak Rules:
//   • Last activity was YESTERDAY → streak++
//   • Last activity was TODAY     → keep streak unchanged
//   • Gap ≥ 2 days               → reset streak to 1 (today counts)
//
// The use case also:
//   • Updates longestStreak when current streak exceeds it
//   • Sets lastActivityAt to now
//   • Returns the updated Progress record
//
// Dependencies (injected via constructor):
//   progressRepo — reads/writes Progress records from the database
//
// Usage (future):
//   const repo = new ProgressRepository();
//   const useCase = new UpdateStreakUseCase(repo);
//   const updated = await useCase.execute('user-123', 'loops-001');
// =============================================================================

import type { Progress } from '@repo/domain';

/** Repository interface — any class that provides these methods can be injected */
interface ProgressRepo {
  getByUserAndTopic(userId: string, topicId: string): Promise<Progress | null>;
  upsert(progress: Progress): Promise<Progress>;
}

export class UpdateStreakUseCase {
  constructor(private progressRepo: ProgressRepo) {}

  /**
   * Recalculate the user's streak for a given topic and persist the update.
   * @param userId  — the authenticated user's ID
   * @param topicId — the topic the user is currently active on
   * @returns The updated Progress record with new streak values
   */
  async execute(userId: string, topicId: string): Promise<Progress> {
    const existing = await this.progressRepo.getByUserAndTopic(userId, topicId);

    const now = new Date();

    if (!existing) {
      // First-ever activity on this topic → create with streak = 1
      const newProgress: Progress = {
        id: '', // generated by the database
        userId,
        topicId,
        problemsSolved: [],
        totalProblems: 0,
        streak: 1,
        longestStreak: 1,
        lastActivityAt: now,
        isTopicComplete: false,
      };
      return this.progressRepo.upsert(newProgress);
    }

    // Calculate streak based on the gap between lastActivityAt and today
    const updatedStreak = this.calculateStreak(
      existing.streak,
      existing.lastActivityAt,
      now
    );

    const updatedLongest = Math.max(existing.longestStreak, updatedStreak);

    const updated: Progress = {
      ...existing,
      streak: updatedStreak,
      longestStreak: updatedLongest,
      lastActivityAt: now,
    };

    return this.progressRepo.upsert(updated);
  }

  // ---------------------------------------------------------------------------
  // Streak Calculation — Pure business logic (no side-effects)
  // ---------------------------------------------------------------------------
  // Returns the new streak value based on the time gap.
  //
  //   yesterday → streak + 1
  //   today     → streak (unchanged)
  //   ≥ 2 days  → 1 (reset, but today counts as day 1)
  // ---------------------------------------------------------------------------
  private calculateStreak(
    currentStreak: number,
    lastActivityAt: Date,
    now: Date
  ): number {
    const lastDate = this.toDateOnly(lastActivityAt);
    const todayDate = this.toDateOnly(now);

    // Difference in calendar days
    const diffMs = todayDate.getTime() - lastDate.getTime();
    const diffDays = Math.round(diffMs / (1000 * 60 * 60 * 24));

    if (diffDays === 0) {
      // Same day — keep streak as-is
      return currentStreak;
    } else if (diffDays === 1) {
      // Consecutive day — increment streak
      return currentStreak + 1;
    } else {
      // Gap of 2+ days — reset streak (today is day 1)
      return 1;
    }
  }

  /**
   * Strips the time component from a Date, leaving only year/month/day.
   * This ensures streak comparison works correctly across timezones.
   */
  private toDateOnly(date: Date): Date {
    return new Date(date.getFullYear(), date.getMonth(), date.getDate());
  }
}
